### ISSUE TITLE
Meaning of ref_camera in annotations3D

### ISSUE THREAD

**Issue by egeozsoy** [CAMMA-public/MVOR#2]
The value of ref_camera in annotations3D doesn't seem to be used anywhere, but the value itself is different, sometimes 0 sometimes 1 or 2. My question is does this value have any meaning? If not, in which coordinate system are the 3d keypoint annotations?

**Comment by vinkle** [comment]
We use the extrinsic camera parameters to project the 3d poses to camera-coordinates then to image coordinates ([see here](https://github.com/CAMMA-public/MVOR/blob/799ec8c709624c6bbc8b6c88accb2192e15a88a6/lib/visualize_groundtruth.py#L645), and the first camera (corresponding to id "1205220174") has been used as the reference camera with identity extrinsic matrix (see camma_mvor_2018.json["cameras_info"]['camParams']["extrinsics"]). So you are right `ref_camera`  in annotations3D doesn't correspond to a reference camera, and we will remove the field in the subsequent release.
