### ISSUE TITLE
Distance from depth image

### ISSUE THREAD

**Issue by guisoares9** [CAMMA-public/MVOR#4]
Hello.

I'm trying to get de distance of a pixel at the depth image. 

I guess the value of each pixel represents the disparity, and then, using the focal length (on annotation) and the baseline of the cameras (wich I dont know) we can calculate distance.

z = f*B/d

The questions are: my assumptions are right? if so what is the baseline of each camera? 

Best regards!

**Comment by vinkle** [comment]
Depth images encode the distance of the object from the camera sensor ([ref](https://en.wikipedia.org/wiki/Range_imaging)). You can directly use the depth image to get the distance.
