### ISSUE TITLE
why only 1 head keypoint?

### ISSUE THREAD

**Issue by greg-is-kub** [CAMMA-public/MVOR#5]
Hi ! 

I would like to know why you choose to use only one keypoint for the head while coco usually use 5 (nose , 2x eyes , 2x ears). Was it because the persons in the database were wearing mask ?

Also what are you exactly pointing with this keypoint?

Thank you in advance for your help!

un strasbourgeois

**Comment by vinkle** [comment]
We will soon release the updated annotations with keypoints in the COCO format.

**Comment by greg-is-kub** [comment]
thank you for your answer! This must be a big work, do you plan  to  release it in a matter of weeks or months?
